name: PR Review Checklist

on:
  pull_request_target:
    types: 
      - opened

jobs:
  pr-review-list:
    name: Post PR Review Checklist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Post initial PR checklist
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
      with:
        token: ${{ secrets.GH_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: '.github/pr-review-checklist.md'